server:
    port: 8080
spring:
    data:
        mongodb:
            host: mongo
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
logging:
    config: classpath:logback-docker.xml