server:
    port: 7002
    error:
        include-message: always
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: recommend-db
    application:
        name: recommend
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5
logging:
    config: classpath:logback.xml
