server:
    port: 7002
    error:
        include-message: always
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: recommend-db
logging:
    config: classpath:logback.xml
