server:
    port: 7000
app:
    product:
        protocol: http
        host: localhost
        service: products
        port: 7001
    recommend:
        protocol: http
        host: localhost
        service: recommends
        port: 7002
    review:
        protocol: http
        host: localhost
        service: reviews
        port: 7003
logging:
    config: classpath:logback.xml
