server:
    port: 8080
spring:
    jpa:
    datasource:
        url: jdbc:mariadb://mariadb/review-db
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
logging:
    config: classpath:logback-docker.xml