server:
    port: 7003
    error:
        include-message: always
spring:
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mariadb://localhost/review-db
        username: user01
        password: user01
    application:
        name: review
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5
logging:
    config: classpath:logback.xml